### ISSUE TITLE
What kind of FilePicker are you guys looking for?

### ISSUE THREAD

**Issue by tommybear** [Mezo-hx/MonoGame.ImGuiNet#12]
What kind of implementation are you guys looking for in the Utils section for the FilePicker? A native file picker for each platform? One for MacOS, Linux and Windows?

Let me know :)

**Comment by Mezo-hx** [comment]
Oh yeah, we (specifically, I) was planning on making it a native one for each platform.

**Comment by tommybear** [comment]
Cool. Well if you'd like. I am using this code and I need a file picker so I need to implement something. So if you are not going to be doing it any time in a hurry, I'm going to be working on it. When it's done, I'll submit it here, if you haven't got something :)

I plan to also port a bunch of the C++ only extensions for the C++ dear Imgui out there to C#/MonoGame.ImGuiNet. So in time, if you have any room for them here or want to link to them in some way, that would be cool. Anyway, I'm going to plug away at some platform code :)

**Comment by tommybear** [comment]
Okay so there is this project excellent clean C project:
https://github.com/mlabbe/nativefiledialog
and then there is this c# version of it:
https://github.com/Speykious/NativeFileDialogs.NET

so you can totally integrate this based on the license or pick from the project.

However, one thing that I have noticed is that this .net project is generated using an AST project called CppSharp which I had forgotten about... simply amazing, the whole project is generated form the c source code. Might need to investigate this.

**Comment by Mezo-hx** [comment]
> So if you are not going to be doing it any time in a hurry, I'm going to be working on it

Yeah, sure, you can do that if you'd like!

> I plan to also port a bunch of the C++ only extensions for the C++ dear Imgui out there to C#/MonoGame.ImGuiNet. So in time, if you have any room for them here or want to link to them in some way, that would be cool

Alright, we'll probably have room for it!
