### ISSUE TITLE
Suggestion: keep the same function names/structure as the original Monogame.ImGui library

### ISSUE THREAD

**Issue by rtsonneveld** [Mezo-hx/MonoGame.ImGuiNet#3]
Since this project is linked as an alternative for the discontinued [Monogame.ImGui](https://github.com/dovker/Monogame.ImGui), it would be neat if the (common) function names and structure would match with the old project, both for people like me who can only refer to old documentation (as it's currently lacking), and for backwards compatibility.

For example:

BeforeLayout was BeginLayout
AfterLayout was EndLayout
The old Initialize function does not seem to exist anymore.

Alternatively you could add these old function names with an Obsolete attribute to indicate it's not used anymore.

**Comment by Mezo-hx** [comment]
Hey! I'll definitely consider this on the update I'm planning on doing soon!
