### ISSUE TITLE
Ctrl and shift keys are not working with InputText.

### ISSUE THREAD

**Issue by LeviMooreDev** [Mezo-hx/MonoGame.ImGuiNet#4]
When using ctrl to copy and paste from and to an InputText the frame rate starts going down until no keyboard input is received.
It takes some seconds before it is up to speed again and able to receive input.
When holding shift it also happens but a little slower.

**Comment by Mezo-hx** [comment]
Hey! I'll check this issue out, and hopefully, it'll be fixed with the next update.

**Comment by LeviMooreDev** [comment]
That sounds great. Any idea when the next update is going to be? I am looking forward to following MonoGame.ImGuiNet.

**Comment by Mezo-hx** [comment]
> That sounds great. Any idea when the next update is going to be? I am looking forward to following MonoGame.ImGuiNet.

Not sure, but maybe in a few weeks? Since I'm having some issues with my computer atm

**Comment by LeviMooreDev** [comment]
If you need any help just ask.

**Comment by Mezo-hx** [comment]
Hey 👋 

The issue should be fixed, and both `BeforeLayout` and `AfterLayout` were renamed to `BeginLayout` and `EndLayout`.
