### ISSUE TITLE
Unhandled exception. System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by PixelDough** [Mezo-hx/MonoGame.ImGuiNet#5]
With the basic implemention set up, I get the following error upon trying to draw anything within the ImGuiRenderer.BeginLayout:
``Unhandled exception. System.MissingMethodException: Method not found: 'ImGuiNET.RangePtrAccessor`1<ImGuiNET.ImDrawListPtr> ImGuiNET.ImDrawDataPtr.get_CmdListsRange()'.
at MonoGame.ImGui.ImGuiRenderer.UpdateBuffers(ImDrawDataPtr drawData)
at MonoGame.ImGui.ImGuiRenderer.RenderDrawData(ImDrawDataPtr drawData) in C:\Users\PixelDoughAdmin\Documents\Repos\monogame_project\Monogame.ImGui\MonoGame.ImGui\ImGUIRenderer.cs:line 104
at MonoGame.ImGui.ImGuiRenderer.EndLayout() in C:\Users\PixelDoughAdmin\Documents\Repos\monogame_project\Monogame.ImGui\MonoGame.ImGui\ImGUIRenderer.cs:line 38``

I've got the ImGuiRenderer initializing, calling "Initialize" on it makes no difference here, and RebuildFontAtlas too. Simply having a BeginLayout and EndLayout causes the crash

**Comment by Mezo-hx** [comment]
Perhaps try installing ImGui.Net Nuget package, and let me know if anything changes or not
![image](https://github.com/Mezo-hx/MonoGame.ImGuiNet/assets/47868851/8cda5930-58af-4e33-9f73-66298ba4a67d)

And for how the code should look:

```
using ImGuiNET;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoGame.ImGuiNet;
using System.Text;

namespace Example
{
    public class Game1 : Game
    {
        private GraphicsDeviceManager _graphics;
        private SpriteBatch _spriteBatch;
        public ImGuiRenderer GuiRenderer;

        public Game1()
        {
            _graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible = true;
        }

        protected override void Initialize()
        {
            GuiRenderer = new ImGuiRenderer(this);
            GuiRenderer.RebuildFontAtlas();

            base.Initialize();
        }

        protected override void LoadContent()
        {
            _spriteBatch = new SpriteBatch(GraphicsDevice);
        }

        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            GuiRenderer.BeginLayout(gameTime);

            ImGui.Begin("Input Text");

            ImGui.Text("a");

            ImGui.End();

            GuiRenderer.EndLayout();

            base.Draw(gameTime);
        }
    }
}
```

(Rather than `EndLayout` and `BeginLayout`, it should be `AfterLayout` and `BeforeLayout`)

**Comment by cherrynik** [comment]
You have two different references on the same assembly, like this:

<details>

<img src="(https://github.com/Mezo-hx/MonoGame.ImGuiNet/assets/32453685/db4f53a6-4262-4d5f-98e0-e39f8aa0cc12"/>

</details>

Solves by remaining single assembly reference in the whole project. I've deleted ImGUINet from my main project, as it wasn't required to even install that. As MonoGame.ImGuiNet has already reference itself on the version it needs.

Hope it helps you.
